export const siteConfig = {
  name: "Gulf Digital Solutions",
  url: "https://gulfdigitalsolution.com",
  description:
    "Professional website design, web advertising, and digital solutions for businesses in Abu Dhabi, Dubai, and across the UAE.",
  keywords: [
    "gulf digital solutions",
    "website design UAE",
    "business website design",
    "web advertising UAE",
    "Abu Dhabi website design",
    "Dubai website design",
    "web advertising services",
    "UAE business websites",
    "digital marketing UAE",
    "professional website maintenance services in dubai",
    "professional website maintenance services in abu dhabi",
    "professional website maintenance services in uae",
    "small business website UAE",
    "professional website design",
    "website maintenance services dubai",
    "website maintenance services abu dhabi",
    "website maintenance services uae",
    "website maintenance services",
    "website maintenance support dubai",
    "website maintenance support abu dhabi",
    "website maintenance support uae",
    "website maintenance support",
    "online advertising dubai",
    "online advertising abu dhabi",
    "online advertising uae",
    "online advertising services",
    "online advertising platform",
  ],
};